name: Tox Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: test
      run: |
        sudo apt update
        sudo apt-get install python3-setuptools
        sudo apt-get install python3-pip
        sudo pip3 install tox
        sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install python3.7
        tox
        
        
